# !!! exampleSite only, set this to your own site URL
baseURL= "localhost"
languageCode= "en-us"
title= "RNK All Day"
theme= ["ryder"]
summaryLength = 15
enableRobotsTXT = true
copyright = "©️ Rian Kochel 2024"
enableEmoji = true
# enableGitInfo = true

[pagination]
  pagerSize = 12 
  