baseURL= "https://rnkallday.com/"
languageCode= "en-us"
title= "Word Nerd: A portfolio of multimedia work by Rian Kochel"
theme= ["word-nerd"]
summaryLength = 15
enableRobotsTXT = true
copyright = "©️ Rian Kochel 2024"
enableEmoji = true
enableGitInfo = true

[pagination]
  pagerSize = 12
