# !!! exampleSite only, set this to your own site URL
baseURL= "localhost"
languageCode= "en-us"
title= "All Day Rian"
theme= ["ryder"]
summaryLength = 15
enableRobotsTXT = true
copyright = "©️ Rian Kochel 2024"
enableEmoji = true
enableGitInfo = true
paginate = 80

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
[params]
  description = 'A theme for hugo'
  TocOpen = true
  # UseHugoToc = true
  # enabledebugpanel = true 
  # navbar_fixed = true
  excludedTags = ["excluded"]
  showDate = false 
  hideAuthor = true 
  hideHomeFeed = true
  headerType = "-rnk"
  showDarkToggle = false 
  showShareButtons = true
  loadLeaflet = true 
  og_image_default = 'images/ryder-theme-og.webp'
  # homePageFeedHeader = "the new style"
  logo_firstWord = 'rnk'
  logo_lastWord = 'all-day'
  # logo_tagline = "FOR HUGO WEBSITES"
  logo_fontClass = 'font-titillium'
  repository = "https://github.com/arts-link/ryder"
  # articleBackgroundStyle = "bg-gradient-to-l from-blue-100 to-green-100 dark:from-blue-800 dark:to-green-800"
  [params.shareButtons]
    networks = [ "twitter", "email", "reddit", "facebook" ]
    size = "small" # small, medium, large
    icon = "solid" # normal, solid, circle, solidcircle
    buttonMargin = "0.2em"  
  [params.author]
    email = 'ben@benstrawbridge.com'
    name = 'Ben Strawbridge'
  [params.footer]
    tagCloud = true
  [params.twClasses]
    headerBackgroundFrameOuter = " text-neutral-900"
    # headerBackgroundFrameInner = "bg-header-ryder h-[300px] bg-cover bg-left"

# [menus]
# [[menus.main]]
#     name = 'Tags'
#     pageRef = '/tags'
#     parent = 'posts'
#     weight = 9990
# [[menus.footer]]
#     name = 'File a Bug or Feature Request'
#     URL = 'https://github.com/arts-link/ryder/issues/new/choose'
#     rel = '_blank'
#     weight = 10
# [[menus.footer]]
#     name = 'Contact Us'
#     pageRef = '/contact'
#     weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.121.1"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"