name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for PostCSS/Tailwind/JS/React)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Check for README.md in public directory
        run: |
          set -e
          found=0
          shopt -s nocaseglob
          for f in public/README.md public/readme.md public/Readme.md public/readme.MD public/README.MD
          do
            if [ -f "$f" ]; then
              echo "::error::Found $f in the public directory. This file should not be deployed."
              found=1
            fi
          done
          shopt -u nocaseglob
          if [ "$found" -eq 1 ]; then
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: rnkallday.com
          force_orphan: true
